### ISSUE TITLE
듀오게시판 

### ISSUE THREAD

**Issue by 5binn** [eCommerce-Team-A/GamePT#11]
## 작업 내용

- riot api로 불러온 데이터를 게시글에 적용

## Todo

- [x] 라디오버튼 그룹으로 포지션 선택
- [x] 모달 창으로 게시글 등록
- [x] 포지션 선택 이미지로 바꾸기
- [x] 티어 표시
- [x] 최근 전적, 승률, kda 표시 
- [x] 포지션별 페이지
- [x] 수정/삭제 팝업으로 띄우기
