### ISSUE TITLE
판매자 승인

### ISSUE THREAD

**Issue by 5binn** [eCommerce-Team-A/GamePT#23]
## 작업 내용

- 판매자 신청을 원하는 회원에게 인증에 필요한 정보를 받은 후, 확인하고 응답

## Todo

- [x] 관리자 등급 설정
- [x] 판매자 등급 설정
- [x] 판매자 신청
- [x] 관리자 확인
- [x] 응답 메일 발송(승인, 거절)
