### ISSUE TITLE
강의 상세 페이지 임시 표시 부분 실제 데이터 삽입 From #17

### ISSUE THREAD

**Issue by wintersky2** [eCommerce-Team-A/GamePT#26]
## 작업 내용

- 담당 전문가 이력, 구매정보의 가격 부분
- 관련 강의에 해당 전문가의 다른 강의 나열

## Todo

- [x] course_detail html의 전문가 이력 부분에 course.author 로 관련 데이터 삽입
- [x] CourseRepository클래스에서 authorId 로 관련 강의들을 요청하는 findByAuthorId 메서드 작성
- [x] CourseService클래스에서 Long 타입으로 authorId를 매개변수로 받아 CourseRepository.findByAuthorId 에서 List<Course>타입으로 데이터 받아 리턴 해주는 courseFindByAuthorId 메서드 생성
- [x] CourseController클래스에서 CourseService.courseFindByAuthorId로 받은 데이터를 courseByexpert 변수명으로 템플릿에 전달.
