### ISSUE TITLE
Course 세부내용(detail) + Course 목록(List) 구현 작업

### ISSUE THREAD

**Issue by wintersky2** [eCommerce-Team-A/GamePT#6]
## 작업 내용

- 강의 상세내용 작업입니다.
- 강의 목록 페이지 작업 입니다.

## Todo

- [x] 강의 상세내용 페이지를 표시해주는 course_detail 템플릿을 만든다.

- [x] /course/detail/{id}로 받은 GET요청으로 해당 Id를 가진 course를 course_detail 템플릿으로 이동시켜주는 showCourseDetail 메서드를 만든다.

- [x] (중간 추가) 병합 내용(회원, 듀오게시판과 연동) 적용.

- [x] course_detail 템플릿을 미리보기 페이지의 Shop Detail 자료를 사용하여 게임 카테고리, 강의 이름, - 전문가 이름, 강의 정보, 가격을 표시한다.

- [x] 강의 세부내용 하단에 목록("/course/list") 링크를 만든다.

- [x] 강의들의 목록을 표시하는 course_list 템플릿을 만든다. 주소는 /course/list 이다.

- [x] 강의들은 카드처럼 한줄에 4개씩 나열한다. 카드당 기본 이미지, 강의명, 강의 소개, 가격, 상세 보기 버튼이 있다.

- [x] 기본 이미지, 강의명, 상세 보기 버튼을 누르면 해당 강의의 상세 페이지로 이동하게한다.

- [x] 최하단에 해당 전문가의 강의를 추가로 나열하는 부분을 구현한다.
